/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#eff4ff",
        "on-surface": "#0b1c30",
        "on-primary-container": "#00422b",
        "on-secondary-fixed": "#111c2d",
        "on-primary-fixed": "#002113",
        "outline-variant": "#bbcabf",
        "tertiary-fixed": "#85f8c4",
        "inverse-surface": "#213145",
        "background": "#f8f9ff",
        "on-surface-variant": "#3c4a42",
        "surface": "#f8f9ff",
        "primary-container": "#10b981",
        "outline": "#6c7a71",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#d5e0f8",
        "tertiary-fixed-dim": "#68dba9",
        "secondary-fixed": "#d8e3fb",
        "on-secondary-fixed-variant": "#3c475a",
        "inverse-primary": "#4edea3",
        "surface-container-highest": "#d3e4fe",
        "primary-fixed-dim": "#4edea3",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-container": "#586377",
        "surface-dim": "#cbdbf5",
        "on-error": "#ffffff",
        "tertiary-container": "#3eb686",
        "on-background": "#0b1c30",
        "secondary": "#545f73",
        "on-tertiary-fixed": "#002114",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "error": "#ba1a1a",
        "primary": "#006c49",
        "secondary-fixed-dim": "#bcc7de",
        "on-primary-fixed-variant": "#005236",
        "tertiary": "#006c4a",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#00422c",
        "surface-tint": "#006c49",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#005137",
        "primary-fixed": "#6ffbbe",
        "surface-container-high": "#dce9ff"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
